### PR TITLE
Rewrite in Golang

### LINKED ISSUE #4: add customisable timeout for http request
if possible

### LINKED ISSUE #11: Should alarming for open file descriptors be disabled?
In a feedback issue @jordansissel stated that alarming on open file descriptors is something that might not be wanted by every user. Since it is already implemented I changed it a bit but left it in the code.

Now my question is wether alarming / thresholds for open file descriptors should be optional e.g. turned off by command line option.

I'll keep it as performance data because this allows for other checks like check_graphite which should be able to detect spike and anormal rises in open file descriptors which might be a thing one wants to be alerted anyway.

Thresholds by now are percents but performance data are actual counts of open file descriptors.

### LINKED ISSUE #14: Error handling on wrong options
Now ruby is left alone with dealing with wrong input

### LINKED ISSUE #15: Provide full support for threshold ranges
Implement all range options for thresholds according to monitoring plugin development guidelines. Don't care if they make sense but make the implementation reusable.

### LINKED ISSUE #32: Make use of the new formatting options in Icinga Web 2
When you write the status like `[OK]` or `[WARNING]` in Icinga Web 2 2.7+ it gets highlighted automatically. No matter if this is part or a multiline output or not.

We should use that.

### LINKED ISSUE #42: --inflight-events-warn and --inflight-events-crit not working correctly. (false positive alarms)
Hello. I have issue using this plugin using custom alarms for inflight-events-warn and inflight-events-crit
Here is the output without parameters:
[root@coreinit check_logstash]# ./check_logstash -H localhost
OK - Logstash seems to be doing fine. | process.cpu.percent=1%;;;0;100 jvm.mem.heap_used_percent=65%;70;80;0;100 jvm.threads.count=58;;;0; process.open_file_descriptors=186;13855;15485;0;16384 pipelines.main.events.out=76185331c;;;0; inflight_events_main=-76786;;;0;
OK: CPU usage in percent: 1
OK: Config reload syntax check: main: OK;
OK: Inflight events: main: -76786;
OK: Heap usage at 65.00% (1374317728 out of 2112618496 bytes in use)
OK: Open file descriptors at 1.14%. (186 out of 16384 file descriptors are open)

Here is the test with parameters --inflight-events-warn 100000 --inflight-events-crit 200000:
[root@coreinit check_logstash]# ./check_logstash -H localhost --inflight-events-warn 100000 --inflight-events-crit 200000
CRITICAL - Logstash is unhealthy - CRITICAL: Inflight events: main: -76624; | process.cpu.percent=1%;;;0;100 jvm.mem.heap_used_percent=53%;70;80;0;100 jvm.threads.count=58;;;0; process.open_file_descriptors=187;13855;15485;0;16384 pipelines.main.events.out=76189183c;;;0; inflight_events_main=-76624;100000;200000;0;
CRITICAL: Inflight events: main: -76624;
OK: CPU usage in percent: 1
OK: Config reload syntax check: main: OK;
OK: Heap usage at 53.00% (1134559128 out of 2112618496 bytes in use)
OK: Open file descriptors at 1.14%. (187 out of 16384 file descriptors are open)

Logstash Version: logstash-7.6.2-1.noarch
Can you help me with this issue ?
Best regards,

### LINKED ISSUE #45: [Feature Request] Select pipeline for inflight events
Hi @widhalmt 
We have a logstash with several pipelines defined, where on the one side, some pipelines always have to get inflight events and on the other side, some only get events on demand. We would like to monitor the inlight events of the important pipelines only and set ranges for them. Currently a range of "1:" triggers alerts, because the "on demand" pipelines are not getting events (or different amounts, so we could use different trigger values)

Cheers,
Marcus

### PR DESCRIPTION
**Pull request by martialblog**
This is a complete rewrite of the Check Plugin in Golang. 

The rationale behind this is first of all maintainability. Since we currently have no Ruby developers, the current implementation cannot be properly maintained. Furthermore it removes dependency management for the user, since we can ship a single binary.

And it fixes a bunch of open issues as described in the milestone.

Fixes #4 

Fixes #11 

Fixes #14 

Fixes #15 

Fixes #32 

Fixes #42 

Fixes #45

### CODE REVIEW

**Comment by martialblog** [comment]
@widhalmt FYI, as discussed.

**Comment by widhalmt** [comment]
Wow, that was fast! Thanks. I'm the wrong person to review it. But, as discussed, I can and will test it. Should I wait for the checks to be ok?

**Comment by martialblog** [comment]
@widhalmt The failing CI checks are just some linting issues. You can go ahead and test it. Do you need a binary or can you build it yourself?

**Comment by martialblog** [comment]
@widhalmt I just added a RC Release with a binary. Feedback is welcome

https://github.com/NETWAYS/check_logstash/releases/tag/v0.8.0-rc1

**Comment by martialblog** [comment]
@pdorschner has already done a Code Review.

**Pull request merged**
