### PR TITLE
Add CLI flag to override exit code if API is unreachable

### LINKED ISSUE #98: [Feature]: connection refused (*url.Error) as CRITICAL or UNKNOWN
### Describe the feature request

Good Morning,
An connection refused error is an indication for a failed logstash instance. Currently the plugin marks this as Unknown. It would be nice to set this as critical.

Cheers,
Marcus

### PR DESCRIPTION
**Pull request by martialblog**
Fixes  #98 

TODO
- [x] Agree on a name for the new flag
- [x] Update README

### CODE REVIEW

**Comment by martialblog** [comment]
@RincewindsHat Not sure about the flag's name yet. Ideas?

**Comment by martialblog** [comment]
I'd like to have a generic CLI flag name so that we can re-use it in different plugins

**Comment by RincewindsHat** [comment]
`critical-if-unreachable` for a really verbose version
`unreachable-state $STATE` for setting the state on the caller side

**Comment by martialblog** [comment]
Would be nice to have an pflag Enum Type, but that's currently not available. Our go-check module fortunately is clever enough to handle things other than 0,1,2,3

**Comment by RincewindsHat** [comment]
Usability? How many people do actually know how the statuses map to integers?

**Comment by martialblog** [comment]
I'd assume that people in the monitoring plugins ecosystem are at least familiar with exit codes and their meaning. I would prefer to keep the code simple and people can read up on stuff IF they need this feature at all

Also - and I realize that this point is far fetched - but what if another monitoring plugin system does not use the same "warning" "critical" "unkown" mapping that Icinga does.

**Comment by RincewindsHat** [comment]
ALL the nagios decendents use the same mapping to my knowledge. If you change that you can just stop using these monitoring plugins at all.
They would be pretty much useless.

But this option can be expanded in the future without breaking the API to the user, so I would say we go for it now with numerical codes only.

I would request a enhancement of the help text for the option though to make it clearer what the `3` means and also maybe what the other options are.

**Comment by martialblog** [comment]
Updated the help text and README

**Review by RincewindsHat — APPROVED** [review]

**Pull request merged**
